### PR TITLE
Update Dashboard.jsx

### PR DESCRIPTION
**Pull request by KrishnaMohanty08**
1. Icons for Stat Cards: Icons from react-icons give a visual cue for each metric, making it more intuitive.
2. Hover Shadow and Transitions: Each component now has a hover shadow effect and a transition for a dynamic feel.
3. Tooltip for Extra Info: Added tooltips for hovering, giving context or extra information on specific data points.
4. Gradient Background: A gradient background adds a modern, polished look to the entire dashboard.
5. Descriptive Texts: Brief, friendly descriptions explain each section’s purpose, giving users more guidance as they explore the dashboard.

### CODE REVIEW

**Comment by shivamyadavrgipt** [comment]
@KrishnaMohanty08 could you share some images

**Comment by KrishnaMohanty08** [comment]
image

**Comment by shivamyadavrgipt** [comment]
@KrishnaMohanty08 brother i am getting 404 error
{131871FD-4A82-4A23-A782-11D18FE66D79}

**Comment by KrishnaMohanty08** [comment]
pull req is closed should i create a new one?
maybe some error

**Comment by shivamyadavrgipt** [comment]
@KrishnaMohanty08 okay

**Pull request merged**
