### PR TITLE
Added a Dedicated "Contribution page"

### PR DESCRIPTION
**Pull request by priyachau12**
Issued #67  resolved

### CODE REVIEW

**Comment by priyachau12** [comment]
image

**Comment by anjany06** [comment]
@priyachau12 HEY can you tell how can you merge pr bcoz i got a netlify error. plz response

**Comment by shivamyadavrgipt** [comment]
@priyachau12 please do resolve conflict

**Comment by priyachau12** [comment]
> @priyachau12 please do resolve conflict

Yes

**Comment by priyachau12** [comment]
I have resolved the conflicts please review it on  #102

**Pull request closed without merging**
