### PR TITLE
Create landing page fix issue #103

### PR DESCRIPTION
**Pull request by mansiruhil13**
Output for landing page:
Fix issue #103
Screenshot 2024-10-15 011637
Screenshot 2024-10-15 011901

### CODE REVIEW

**Comment by mansiruhil13** [comment]
@shivamyadavrgipt please review

**Comment by shivamyadavrgipt** [comment]
@mansiruhil13 code is not getting error

**Comment by mansiruhil13** [comment]
> @mansiruhil13 code is not getting error

but its' not showing in final

**Comment by mansiruhil13** [comment]
labels??

**Comment by shivamyadavrgipt** [comment]
@mansiruhil13 done

**Pull request merged**
