### PR TITLE
i have done the changes...

### PR DESCRIPTION
**Pull request by SaanyaGarg5**

### CODE REVIEW

**Comment by SaanyaGarg5** [comment]
pls check...and let me know

**Comment by SaanyaGarg5** [comment]
pls check and let me know..

**Comment by shivamyadavrgipt** [comment]
@SaanyaGarg5 please do mention issue number

**Comment by SaanyaGarg5** [comment]
PR#66

**Comment by SaanyaGarg5** [comment]
kindly merge and give me the points
also add labels level 3 , gssoc-ext,hacktoerfest

**Comment by SaanyaGarg5** [comment]
issue number is #53

**Comment by shivamyadavrgipt** [comment]
@SaanyaGarg5 is code is running on your systembecause i m getting an error

**Comment by SaanyaGarg5** [comment]
Yes it is running

**Comment by SaanyaGarg5** [comment]
Pls add labels

**Comment by shivamyadavrgipt** [comment]
@SaanyaGarg5 kindly share some images or video

**Comment by SaanyaGarg5** [comment]
You have merged but not added the labels..kindly add them

**Comment by SaanyaGarg5** [comment]
@shivamyadavrgipt  kindly add level

**Comment by shivamyadavrgipt** [comment]
@SaanyaGarg5 sure i am adding but please do share the images

**Comment by SaanyaGarg5** [comment]
> @SaanyaGarg5 sure i am adding but please do share the images

Yes

**Comment by shivamyadavrgipt** [comment]
@SaanyaGarg5 i m waiting

**Comment by SaanyaGarg5** [comment]
Screenshot (295)
Screenshot (294)
Screenshot (296)

**Comment by shivamyadavrgipt** [comment]
@SaanyaGarg5 not this give image of fronted screenshot

**Comment by SaanyaGarg5** [comment]
Yes

**Comment by shivamyadavrgipt** [comment]
@soniya-malviy

**Comment by SaanyaGarg5** [comment]
but my code has no errors, you can run them

**Comment by shivamyadavrgipt** [comment]
{95BF72F0-9479-4A40-A6D0-B45663A943E6}

**Comment by SaanyaGarg5** [comment]
just check : blogs.js,blogs_style.css

**Pull request merged**
