### PR TITLE
Tailwind CSS setup & also working & all typo fix and also "settings" issue resolve, working new deployment also created on vercel 👍 

### PR DESCRIPTION
**Pull request by Arnab7456**
add Tailwind into the project

Screenshot 2024-10-05 014130

and also Working 

image

### CODE REVIEW

**Comment by Arnab7456** [comment]
This may have caused a production failure issue, as per your README.md, you mention that '📱 Responsive UI - Optimized for both desktop and mobile devices using Tailwind CSS,' but the tailwind.config.js file is not present. I would like to contribute by adding it, along with screenshots. Please consider this, so that new contributors can effectively use Tailwind CSS in your project

**Comment by Arnab7456** [comment]
can you add this pr @shivamyadavrgipt

**Comment by soniya-malviy** [comment]
Arnab7456 your file have some conflict resolve them.

**Comment by soniya-malviy** [comment]
> can you add this pr @shivamyadavrgipt

Arnab7456 your file have some conflict resolve them.

**Pull request closed without merging**
